### PR TITLE
PD-4866 Replace decrypt-and-start bash script with python script

### PR DESCRIPTION
**Pull request by agaffney**

### CODE REVIEW

**Comment by agaffney** [comment]
A quick side-by-side test with a single encrypted var shows that the python scripts shaves off 0.1s in execution time.

**Comment by agaffney** [comment]
```
# Python 2
$ time python scripts/decrypt-and-start env >/dev/null

real	0m0.666s
user	0m0.170s
sys	0m0.029s
# Python 3
$ time python3 scripts/decrypt-and-start env >/dev/null

real	0m0.608s
user	0m0.235s
sys	0m0.024s
# Bash
$ time decrypt-and-start env >/dev/null

real	0m0.706s
user	0m0.317s
sys	0m0.068s
```

**Comment by agaffney** [comment]
The time difference is even more drastic with 5 encrypted vars.

```
# Bash
$ time decrypt-and-start env >/dev/null

real	0m3.246s
user	0m1.365s
sys	0m0.187s
# Python
$ time scripts/decrypt-and-start env >/dev/null

real	0m2.115s
user	0m0.392s
sys	0m0.059s
```

**Review by sathvik-dhanya — APPROVED** [review]
LGTM

**Review by ghost — APPROVED** [review]

**Pull request merged**
